CREATE DATABASE blossom_db;

use blossom_db;

CREATE TABLE tasks (   
    task_id INT PRIMARY KEY AUTO_INCREMENT,   
    title VARCHAR(255) NOT NULL,   
    is_completed BOOLEAN NOT NULL DEFAULT false 
    );

INSERT INTO tasks (title, is_completed) VALUES
('Climb a mountain and see a beautiful view in Thailand', 0),
('Travel together in China and eat lots of delicious food!', 0),
('Replay It Takes Two together all over again.', 0),
('Make a pizza together', 0),
('Orlando Disney World, need I say more?', 0),
('Japan - Trip to Tokyo, eat and drink authentic sushi and sake', 0),
('Start a band together and make some music!', 0),
('Design a website or business together', 0),
('Go to more paint nights together', 0),
('See the Lakeshore Christmas lights together again!', 0),
('Romantic evening in the underwater hotel in Australia', 0),
('Do couples yoga together', 0),
('Go swimming in the ocean together', 0),
('Own a cute little doggy together- Hiberbear', 0),
('Go scuba diving in Great Barrier Reef together', 0),
('Grow and raise a plant together and watch it grow!', 0),
('Build a tent together when we go camping', 0),
('Teach u how to clean a fish - if u dare to haha', 0),
('Take u tubing on the lake with our boat', 0),
('Meet your family in person together and get to know them all well', 0),
('Go skydiving or paragliding together', 0),
('Go to Lake Louise together and take a vile of water home as a memory', 0),
('Bike together all around Stanley Park island in Vancouver', 0),
('Go ocean fishing with u on a private chartered boat', 0),
('Take u flying as my first passenger', 0),
('Be your driving instructor so u can get your G license!', 0),
('Watch u get your dream job and finally get the work-life balance and salary u deserve!', 0),
('Get a swimming pass so we can go swimming together whenever we want', 0),
('Decorate an apartment and pick all the furniture and style together', 0),
('Go purse shopping so u can get any one that catches your fancy ;)', 0),
('Watch the White Lotus S2 together', 0),
('Make new year dumplings with your family in China', 0),
('Bring me to eat authentic luosifen mian and yaxuetang mian', 0),
('Go see the Great Wall together in the morning so there\'s less people and we can enjoy the view ourselves!', 0),
('Try the Korean spicy noodles challenge with u', 0),
('Start vlogging or making videos with u about our travel on Bilibili', 0),
('Eat some knife-cut noodles together in Tangshan', 0),
('Eat authentic Peking duck in Beijing', 0),
('Take Ollie and Henry and you to see an aquarium or Ripley\'s museum together', 0),
('Buy our first house or chalet/cottage together using first-time buyers tax benefit!', 0),
('Let u eat my grandma\'s delicious authentic Italian food', 0),
('Together teach more English with your mom so we can all have our secret language in China so that no one else can understand ;)', 0),
('Take u acting on a movie set and show u how everything works :D give u the opportunity to be famous and I\'ll forever be known as Danni Zou\'s boyfriend haha', 0),
('Let u cut my hair', 0),
('Try some relaxing hot springs in Japan', 0),
('Play some baseball together at the diamond near my house', 0),
('Take u rock climbing on our next anniversary', 0),
('Take a shower together!!!!!!! ;P', 0),
('Take you to a Blue Jays game in Toronto', 0),
('Have a romantic dinner with an ocean view with just the two of us!', 0),
('Buy your favorite chips flavor snacks and eat them with u', 0),
('More and more concerts, Doja Cat is a must!', 0),
('Shred the gnarliest rip with you on our snowboards in Whistler mountain', 0),
('We both become fluent in Chinese and English together so we can have the best communication which will only strengthen our relationship!', 0),
('Let u teach me some guitar basics', 0),
('Sing Chinese children songs together with your niece', 0),
('Work together as CEO and CFO in our own company that makes us millions of dollars', 0),
('Play cribbage together again every year', 0),
('Send u cute good morning texts that make your morning', 0),
('Spontaneously surprise you with breakfast', 0),
('Take u to Japanese Mario world, itsaa meeee mama Mia!', 0),
('Rub and scratch your back every day', 0),
('Just make u laugh and see you smile', 0),
('Go get a nice massage together when we\'re stressed out', 0),
('Play more board games together with your friends, I\'ll secretly be on your team ;)', 0),
('Go kiss you again on that park bench beside the Rideau Canal and watch the Canada day fireworks', 0),
('Go enjoy the beautiful Quebec Scandinavian spa', 0),
('Take you on top of the CN Tower', 0),
('Take you to a dancing class where you can really have some fun!', 0),
('Go to a casino and win something, bet it all on black!', 0),
('Carve our initials into an old old tree so that our love will be snapshotted for a long long time!', 0),
('Do the sexy time in every room of our new apartment', 0),
('Couples Halloween costumes, this one\'s wayyyy past due, we need to do this hehe', 0),
('Go enjoy a beautiful orchestra concert of classic music in the theater', 0),
('Buy our Tesla for me and Mustang for you. Oooooh and the golden Lamborghini (this is a must)', 0),
('Go horseback riding', 0),
('Take a road trip to the east coast and smell the fresh ocean air and eat the amazing sea food', 0),
('Find some lost treasure while metal detecting with u', 0),
('Go see Avatar 2 together ;)', 0),
('Treat u to a multi-course meal dinner at a fancy expensive restaurant', 0),
('Go skinny dipping', 0),
('Have a relaxing evening drinking some wine inside the hot tub in our backyard', 0),
('Have a movie/date night where we must cuddle up and watch a movie together on our giant projector screen :D', 0),
('Go see the northern lights together and have a romantic kiss under the stars, hopefully it\'s not so cold our lips get stuck together!', 0),
('Read a book together, English and Chinese', 0),
('Create our very own secret handshake that no one else knows so that we can tell if the other is ever eaten by a shape-shifting alien.', 0),
('Get tattoos together!', 0),
('Take you to Italy so you can also experience my motherland!', 0),
('Make your mom a delicious Italian pizza', 0),
('Do small renovations on our first home together as a couples project', 0),
('Grow and tend to a beautiful garden together', 0),
('Go see the kite flying festival in China', 0),
('Go see the Mexican pyramids in person to appreciate ancient history!', 0),
('Go camping in Algonquin park, I\'ll bring my telescope and we can watch out for aliens and bears haha', 0),
('Go watch a drive-in movie together', 0),
('Spend all day together kissing just like the early days :D', 0),
('Go volunteer somewhere together to bring us some food karma!', 0),
('Go to the gym and stay healthy together!', 0),
('Have an epic dinner party at our apartment and invite all of our friends!', 0),
('Love each other forever', 0);


SELECT * FROM blossom_db.tasks
